In [1]:
import os, re
import numpy as np
import pickle as pkl

In [2]:
input_folder = "../data/preprocessed_tika/"


In [3]:
file_to_text = {}
for root, folder, files in os.walk(input_folder):
    for file_name in files:
#         if not (file_name.startswith("TB") or file_name.startswith("HIV")):
#             continue
        if not file_name.endswith("pkl"):
            continue
        pdf_file = re.sub(".pkl", "", file_name)
        
        full_file = input_folder + "/" + file_name
#         print (full_file)
        with open(full_file, 'rb') as f:
            text = pkl.load(f)
        file_to_text[pdf_file] = text

In [4]:
from sklearn.model_selection import train_test_split


In [5]:
words = []
categories = []

for file, pages in file_to_text.items():
    
        
    cat = 0
    repetitions = 1
    if file.startswith("HIV"):
        cat = 1
        repetitions = 2
    elif file.startswith("TB"):
        cat = 2
        repetitions = 4
    
    for j in range(repetitions):
        words.append(" ".join(pages))
        categories.append(cat
                         )

In [6]:
from collections import Counter
Counter(categories)

Counter({2: 48, 1: 48, 0: 40})

In [7]:
features_train, features_test, labels_train, labels_test = train_test_split(words, categories, test_size=0.1, random_state=10)


In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer, HashingVectorizer


In [56]:
from sklearn.pipeline import make_pipeline
from sklearn.naive_bayes import MultinomialNB

from nltk.tokenize import RegexpTokenizer

tok = RegexpTokenizer(r'[a-zA-Z]+')

In [85]:
from nltk.corpus import stopwords

stops = set(stopwords.words('english')).union( set(stopwords.words('french')))


In [112]:
stops = stops.union({
    "title",
    "study",
    "protocol",
    "participant",
    "participants"
    "irb",
    "africa",
    "trial",
    "patient",
    "patients",
    "treatment",
    "data",
    'safety',
 'efficacy',
 'short',
 'trial',
 'irb',
 'gov',
 'sponsor',
 'university',
 'delivery',
 'co',
 'usa',
 'phone',
 'edu',
 'principal',
 'investigators',
 'laboratory',
 'department',
 'us',
 'email',
 'institute',
 'centre',
 'com',
 'confidentiality',
 'document',
 'confidential',
 'information',
 'must',
 'investigator',
 'team',
 'relevant',
 'ethics',
 'regulatory',
 'contents',
 'research',
 'non',
 'registration',
 'data',
 'summary',
 'background',
 'rationale',
 'primary',
 'objective',
 'hypothesis',
 'overview',
 'design',
 'sites',
 'population',
 'interventions',
 'outcome',
 'measures',
 'follow',
 'procedures',
    'repeat',
 'drug',
 'control',
 'diseases',
 'sample',
 'size',
 'analysis',
 'introduction',
'disease',
 'repeated',
 'effects',
 'prevalence',
 'needed',
 'ongoing',
 'objectives',
 'secondary',
 'determine',
 'effect',
 'number',
 'time',
 'treated',
 'per',
 'years',
 'age',
 'rate',
 'adult',
 'considerations',
 'unit',
 'children',
 'intervention',
 'model',
 'assignment',
 'arms',
 'eligibility',
 'criteria',
 'receiving',
 'inclusion',
 'exclusion',
 'active',
 'case',
 'surveillance',
 'cohort',
 'handling',
 'product',
 'storage',
 'assessment',
 'discontinue',
 'future',
 'studies',
 'adherence',
 'strategies',
 'retention',
 'prior',
 'concomitant',
 'therapy',
 'medications',
 'self',
 'endpoints',
 'outcomes',
 'cumulative',
 'incidence',
 'enrolled',
 'period',
 'assessed',
 'examination',
 'tolerability',
 'participants',
 'recruitment',
 'phase',
 'enrollment',
 'clinical',
 'eligible',
 'subjects',
 'administration',
 'visits',
 'detection',
 'adverse',
 'events',
 'monitoring',
 'sampling',
 'post',
 'endpoint',
 'strategy',
 'allocation',
 'collection',
 'management',
 'diagnosis',
 'testing',
 'methods',
 'statistical',
 'profile',
 'baseline',
 'characteristics',
 'populations',
 'receive',
 'missing',
 'interim',
 'reporting',
 'definitions',
 'event',
 'ae',
 'reaction',
 'serious',
 'sae',
 'suspected',
 'unexpected',
 'severe',
 'reports',
 'quality',
 'training',
 'tests',
 'risk',
 'reduction',
 'plan',
 'ethical',
 'approval',
 'review',
 'process',
 'informed',
 'consent',
 'forms',
 'protection',
 'individual',
 'interest',
 'access',
 'source',
 'documents',
 'benefits',
 'risks',
 'benefit',
 'community',
 'care',
 'health',
 'results',
 'result',
 'impact',
 'drugs',
 'appendix',
 'development',
 'ii',
 'reference',
 'group',
 'purpose',
 'independent',
 'monitor',
 'iii',
 'iv',
 'guidelines',
 'aes',
 'saes',
 'following',
 'ci',
 'confidence',
 'interval',
 'based',
 'combination',
 'al',
 'maximum',
 'concentration',
 'record',
 'form',
 'center',
 'committee',
 'fda',
 'good',
 'practice',
 'global',
 'international',
 'requirements',
 'human',
 'use',
 'institutional',
 'board',
 'treat',
 'long',
 'national',
 'program',
 'randomized',
 'controlled',
 'rapid',
 'diagnostic',
 'test',
 'sop',
 'standard',
 'procedure',
 'sub',
 'world',
 'organization',
 'dr',
 'md',
 'date',
 'support',
 'na',
 'contact',
 'public',
 'scientific',
 'countries',
 'condition',
 'single',
 'performed',
 'start',
 'followed',
 'every',
 'three',
 'weeks',
 'type',
 'blind',
 'prevention',
 'first',
 'target',
 'approximately',
 'persons',
 'meet',
 'within',
 'total',
 'status',
 'given',
 'course',
 'key',
 'site',
 'able',
 'give',
 'parent',
 'monitored',
 'outside',
 'medical',
 'illness',
 'participation',
 'infant',
 'week',
 'birth',
 'known',
 'defined',
 'fever',
 'history',
 'last',
 'hours',
 'may',
 'determined',
 'across',
 'mortality',
 'distribution',
 'increased',
 'however',
 'many',
 'resistance',
 'used',
 'issues',
 'implementation',
 'existing',
 'communities',
 'cost',
 'high',
 'rates',
 'including',
 'would',
 'current',
 'occurring',
 'year',
 'like',
 'region',
 'demonstrated',
 'dose',
 'highly',
 'effective',
 'scale',
 'conduct',
 'reduce',
 'important',
 'inform',
 'starting',
 'well',
 'among',
 'randomization',
 'two',
 'arm',
 'soon',
 'plus',
 'intervals',
 'conducted',
 'main',
 'groups',
 'entire',
 'received',
 'due',
 'perform',
 'occur',
 'visit',
 'times',
 'also',
 'collected',
 'detect',
 'power',
 'using',
 'evaluate',
 'differences',
 'taking',
 'throughout',
 'adjusted',
 'reported',
 'compare',
 'potential',
 'factors',
 'considered',
 'regression',
 'table',
 'schedule',
 'month',
 'recording',
 'cause',
 'http',
 'www',
 'limited',
 'observed',
 'less',
 'proportion',
 'onset',
 'subsequent',
 'increase',
 'developed',
 'child',
 'likely',
 'cases',
 'limit',
 'country',
 'although',
 'general',
 'negative',
 'method',
 'via',
 'least',
 'expected',
 'estimated',
 'life',
 'adults',
 'since',
 'recommended',
 'still',
 'reasons',
 'low',
 'could',
 'twice',
 'area',
 'associated',
 'specified',
 'activity',
 'pharmacokinetic',
 'specific',
 'causing',
 'death',
 'approved',
 'early',
 'relative',
 'shown',
 'either',
 'directly',
 'note',
 'concentrations',
 'days',
 'respectively',
 'significant',
 'field',
 'day',
 'survival',
 'vs',
 'pre',
 'one',
 'different',
 'volunteers',
 'mean',
 'ml',
 'second',
 'even',
 'members',
 'calculated',
 'initial',
 'direct',
 'whether',
 'consistent',
 'daily',
 'young',
 'become',
 'line',
 'changes',
 'seen',
 'might',
 'presence',
 'later',
 'figure',
 'right',
 'combined',
 'present',
 'related',
 'system',
 'large',
 'doses',
 'administered',
 'indicated',
 'dosing',
 'mild',
 'reactions',
 'occurs',
 'take',
 'physician',
 'women',
 'comparison',
 'mothers',
 'found',
 'findings',
 'confirmed',
 'loss',
 'longer',
 'excluded',
 'regimens',
 'severity',
 'individuals',
 'currently',
 'trials',
 'frequency',
 'months',
 'back',
 'pain',
 'healthy',
 'similar',
 'placebo',
 'toxicity',
 'detected',
 'multiple',
 'versus',
 'org',
 'common',
 'overall',
 'continue',
 'required',
 'june',
 'october',
 'need',
 'necessary',
 'effectiveness',
 'prevent',
 'missed',
 'greater',
 'entry',
 'resistant',
 'recent',
 'assays',
 'exposure',
 'costs',
 'completed',
 'double',
 'change',
 'compared',
 'another',
 'planned',
 'previous',
 'higher',
 'assess',
 'whole',
 'local',
 'additional',
 'monthly',
 'nc',
 'blinded',
 'measured',
 'survey',
 'september',
 'tested',
 'analyses',
 'order',
 'made',
 'thus',
 'get',
 'family',
 'person',
 'previously',
 'help',
 'measure',
 'four',
 'selected',
 'addition',
 'tablets',
 'responsible',
 'household',
 'weight',
 'insert',
 'place',
 'provided',
 'maintained',
 'records',
 'stored',
 'staff',
 'products',
 'appropriate',
 'conditions',
 'label',
 'ensure',
 'receipt',
 'return',
 'signed',
 'personnel',
 'copies',
 'instructions',
 'accordance',
 'end',
 'subject',
 'withdrawal',
 'stage',
 'asked',
 'reason',
 'except',
 'activities',
 'point',
 'past',
 'recorded',
 'crfs',
 'discontinued',
 'term',
 'samples',
 'identification',
 'noted',
 'request',
 'check',
 'scheduled',
 'referred',
 'hospital',
 'clinic',
 'page',
 'taken',
 'diagnosed',
 'refer',
 'temperature',
 'make',
 'small',
 'include',
 'meeting',
 'questions',
 'assigned',
 'written',
 'open',
 'sign',
 'census',
 'questionnaire',
 'code',
 'identify',
 'example',
 'obtained',
 'demographic',
 'values',
 'provide',
 'urine',
 'according',
 'signs',
 'report',
 'set',
 'symptoms',
 'working',
 'evaluation',
 'available',
 'clinically',
 'value',
 'difference',
 'upon',
 'obtain',
 'estimate',
 'lab',
 'identified',
 'lancet',
 'counts',
 'cells',
 'elisa',
 'entered',
 'detailed',
 'final',
 'drawn',
 'unblinding',
 'presented',
 'flow',
 'descriptive',
 'statistics',
 'parameters',
 'comparisons',
 'variable',
 'included',
 'id',
 'classified',
 'failure',
 'measurement',
 'derived',
 'require',
 'providing',
 'compliance',
 'possible',
 'count',
 'ratio',
 'variables',
 'basis',
 'medication',
 'random',
 'occurrence',
 'listed',
 'moderate',
 'services',
 'pdf',
 'requires',
 'work',
 'assessments',
 'rights',
 'described',
 'unless',
 'stopping',
 'relationship',
 'response',
 'investigational',
 'expression',
 'evidence',
 'threatening',
 'hospitalization',
 'immediately',
 'definition',
 'applicable',
 'grade',
 'allow',
 'follows',
 'develop',
 'alternative',
 'occurred',
 'minimal',
 'mail',
 'full',
 'regulations',
 'copy',
 'section',
 'yes',
 'initiation',
 'confirm',
 'remain',
 'acceptable',
 'completion',
 'complete',
 'agree',
 'address',
 'member',
 'involved',
 'read',
 'third',
 'grading',
 'weekly',
 'april',
 'preparation',
 'reviewed',
 'without',
 'amended',
 'amendment',
 'participate',
 'regardless',
 'text',
 'signature',
 'collect',
 'genetic',
 'personal',
 'disclosure',
 'list',
 'regarding',
 'kept',
 'regimen',
 'volume',
 'free',
 'level',
 'otherwise',
 'project',
 'immediate',
 'medicine',
 'levels',
 'added',
 'minimum',
 'designated',
 'infect',
 'dis',
 'mm',
 'documentation',
 'med',
 'int',
 'soc',
 'im',
 'systemic',
 'database',
 'six',
 'normal',
 'randomised',
 'van',
 'manual',
 'decision',
 'version',
 'doctor',
 'lead',
 'experience',
 'exposed',
 'modified',
 'stopped',
 'description',
 'vital',
 'participating',
 'name',
 'inferiority',
 'exploratory',
 'settings',
 'prohibited',
 'median',
 'enrolment',
 'details',
 'separate',
 'measurements',
 'range',
 'solicited',
 'specimens',
 'stop',
 'several',
 'ask',
 'side',
 'problems',
 'please',
 'know',
 'facility',
 'august',
 'home',
 'body',
 'original',
 'march',
 'art',
 'dated',
 'upper',
 'november',
 'aids',
 'counselling',
 'july',
 'fax',
 'mailto',
 'randomisation',
 'social',
 'culture',
 'school',
 'nih',
 'pi',
 'tb',
 'log',
 'exact',
 'tables',
 'haart',
 'immune',
 'dl',
 'duration',
 'approach',
 'adolescents',
 'selection',
 'updated',
 'responses',
 'evaluated',
 'manager',
 'deaths',
 'cannot',
 'therefore',
 'usual',
 'routine',
 'best',
 'next',
 'unknown',
 'december',
 'cohorts',
 'lower',
 'equal',
 'includes',
 'proposed',
 'chest',
 'containing',
 'men',
 'mother',
 'function',
 'interview',
 'discontinuation',
 'potentially',
 'search',
 'symptom',
 'sided',
 'sensitivity',
 'special',
 'minutes',
 'markers',
 'electronic',
 'components',
 'agents',
 'definite',
 'specimen',
 'done',
 'acute',
 'docx',
 'assay',
 'algorithm',
 'candidate',
 'physical',
 'documented',
 'promise',
 'success',
 'component',
 'protective',
 'load',
 'evaluations',
 'male',
 'summarized',
 'late',
 'percentage',
 'hour',
 'points',
 'unsolicited',
 'january',
 'screen',
 'box',
 'window',
 'female',
 'chemistry',
 'room',
 'medicines',
 'referral',
 'reactive',
 'conversion',
 'tube',
 'discretion',
 'designee',
 'interference',
 'parameter',
 'intensive',
 'baby',
 'absolute',
 'prep',
 'pk',
 'maternal',
 'diary',
 'postpartum',
 'template',
 'presentation',
 'author',
    
})

In [113]:
import pycountry
for c in pycountry.countries:
    for t in tok.tokenize(c.name.lower()):
        stops.add(t)

In [140]:
for c in ["A&H",
"Abbott",
"Actelion",
"Aesica pharmaceuticals",
"Air Products",
"Alcon",
"ALK-Abelló",
"Allergan",
"Alpharma",
"Almus Pharmaceuticals",
"Altana",
"Amgen",
"APS",
"Assertio",
"AstraZeneca",
"Aventis Pharma",
"Bausch & Lomb",
"Baxter",
"Baxter BioScience",
"Bayer",
"Becton Dickinson",
"Beiersdorf",
"Berk",
"Biogen",
"Boehringer Ingelheim",
"Boots",
"BPL",
"Braun",
"Bristol-Myers Squibb",
"Celltech",
"Cephalon",
"Chemidex",
"Chugai",
"Colgate-Palmolive",
"Coloplast",
"ConvaTec",
"Cow & Gate",
"CP",
"Crookes",
"Dentsply",
"Dista",
"DuPont",
"Eisai",
"Ethicon",
"Fabre",
"Ferring",
"Florizel",
"Fresenius SE",
"Galderma",
"Galpharm Healthcare",
"Garnier",
"GE Healthcare",
"Gilead",
"GlaxoSmithKline",
"Grünenthal",
"Grifols",
"GSK",
"GSK Consumer Healthcare",
"Heinz",
"Hillcross",
"Hoechst Marion Roussel",
"Invicta",
"Ipsen",
"ITH Pharma Ltd",
"IVAX",
"J&J",
"J&J Medical",
"J&J MSD",
"Janssen-Cilag",
"King",
"Kyowa Hakko",
"Lederie",
"LEO",
"LifeScan",
"Lilly",
"Lundbeck",
"Martindale Pharma",
"Mölnlycke",
"Mayne",
"McNeil",
"Meda",
"Medac",
"MediSense",
"Menarini",
"Menarini Diagnostics",
"Merck",
"Merck Consumer Health",
"Merck & Co.",
"Milupa",
"MSD",
"Nestlé",
"Nestlè Clinical",
"Neutrogena",
"Novartis",
"Novartis Consumer Health",
"Novo Nordisk",
"Nycomed",
"Octapharma",
"Oral B Labs",
"Orion",
"Otsuka",
"Parke-Davis",
"Pfizer",
"Pharmacia",
"Procter & Gamble",
"Procter & Gamble Pharm.",
"Reckitt Benckiser",
"Rhône-Poulenc",
"Roche",
"Roche Consumer Health",
"Roche Diagnostics",
"Rosemont",
"Rybar",
"Salts",
"Sandoz",
"Sankyo",
"Sanofi-Aventis",
"Sanofi Oasteur",
"Sanofi-Synthélabo",
"Schering-Plough",
"Schwarz",
"Searle",
"Serono",
"Servier",
"Shire",
"SHS",
"Sigma",
"SMA Nutrition",
"SNBTS",
"Solvay",
"Squibb",
"SSL",
"Stiefel",
"Takeda",
"Taro",
"Teva",
"Thornton & Ross",
"Trinity-Chiesi",
"Tyco",
"Univar",
"Valeant",
"Viatris",
"W-L",
"Warner Lambert",
"Wockhardt",
"Wyeth",
"Yamanouchi"]:
    for t in tok.tokenize(c.lower()):
        stops.add(t)

In [141]:
vectoriser = TfidfVectorizer(stop_words=stops,min_df=5,max_features=1000,
                              token_pattern=r'(?u)\b[a-zA-Z][a-zA-Z]+\b'
#                                vocabulary={"hiv", "tb", "tuberculosis"}
#                               ngram_range=(2, 2)
                              )
nb = MultinomialNB()
model = make_pipeline(vectoriser, nb)


In [142]:
len(features_train)

122

In [143]:
model.fit(features_train, labels_train)

Pipeline(steps=[('tfidfvectorizer',
                 TfidfVectorizer(max_features=1000, min_df=5,
                                 stop_words={'a', 'abbott', 'abell', 'able',
                                             'about', 'above', 'absolute',
                                             'acceptable', 'access',
                                             'accordance', 'according',
                                             'across', 'actelion', 'active',
                                             'activities', 'activity', 'acute',
                                             'added', 'addition', 'additional',
                                             'address', 'adherence', 'adjusted',
                                             'administered', 'administration',
                                             'adolescents', 'adult', 'adults',
                                             'adverse', 'ae', ...},
                                 token_pattern='(?u)\\b[a-zA-Z][a

In [144]:
labels_train

[0,
 2,
 1,
 1,
 0,
 1,
 2,
 0,
 2,
 2,
 1,
 1,
 1,
 0,
 2,
 1,
 2,
 0,
 1,
 0,
 1,
 2,
 0,
 2,
 0,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 2,
 2,
 0,
 2,
 1,
 2,
 1,
 2,
 0,
 1,
 1,
 0,
 2,
 2,
 1,
 2,
 0,
 2,
 2,
 2,
 0,
 2,
 1,
 2,
 1,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 2,
 1,
 2,
 0,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 0,
 1,
 2,
 2,
 1,
 0,
 0,
 0,
 2,
 0,
 2,
 2,
 0,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 1]

In [145]:
vectoriser.vocabulary_

{'mass': 527,
 'malaria': 524,
 'phd': 643,
 'infectious': 445,
 'immunology': 427,
 'mobile': 553,
 'sciences': 800,
 'revision': 778,
 'contains': 219,
 'host': 403,
 'institution': 458,
 'committees': 194,
 'authorities': 91,
 'summaries': 869,
 'partner': 624,
 'transmission': 917,
 'blood': 122,
 'feeding': 344,
 'mda': 532,
 'sustained': 879,
 'aim': 35,
 'plasmodium': 649,
 'acquired': 16,
 'intensity': 461,
 'transmitted': 918,
 'infections': 444,
 'subset': 863,
 'capture': 139,
 'captured': 140,
 'focus': 354,
 'village': 962,
 'cluster': 187,
 'setting': 820,
 'areas': 73,
 'accountability': 10,
 'removal': 748,
 'permitted': 638,
 'episodes': 315,
 'pregnant': 668,
 'breastfeeding': 126,
 'unscheduled': 944,
 'parasite': 620,
 'molecular': 557,
 'infection': 443,
 'blinding': 121,
 'episode': 314,
 'hemoglobin': 398,
 'stool': 852,
 'head': 393,
 'screening': 803,
 'treatments': 920,
 'termination': 898,
 'causality': 150,
 'expedited': 328,
 'regular': 744,
 'recipients': 

In [146]:
vectoriser.transform(features_train).todense()

matrix([[0.01145787, 0.00225601, 0.00387642, ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.00158575, ..., 0.        , 0.00860322,
         0.03937836],
        [0.0329989 , 0.00140484, 0.00362081, ..., 0.00214082, 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.00442728, ..., 0.        , 0.        ,
         0.01047058],
        [0.        , 0.00192597, 0.00496397, ..., 0.        , 0.        ,
         0.        ],
        [0.00239213, 0.00188401, 0.00161861, ..., 0.01148408, 0.        ,
         0.00143551]])

In [147]:
model.predict_proba(["potato"])

array([[0.31147541, 0.3442623 , 0.3442623 ]])

In [148]:
model.predict_proba(["hiv"])

array([[0.08541374, 0.69326162, 0.22132463]])

In [149]:
model.predict_proba(["tb"])

array([[0.31147541, 0.3442623 , 0.3442623 ]])

In [150]:
nb.coef_

/home/thomas/anaconda3/lib/python3.9/site-packages/sklearn/utils/deprecation.py:101: FutureWarning: Attribute coef_ was deprecated in version 0.24 and will be removed in 1.1 (renaming of 0.26).
  warnings.warn(msg, category=FutureWarning)


array([[-6.68622949, -6.96823037, -6.95212225, ..., -7.00039458,
        -6.9390307 , -7.10303662],
       [-6.77916347, -7.06602335, -6.96379795, ..., -6.95875966,
        -7.12408218, -7.01678246],
       [-7.0274713 , -7.03863866, -7.0785671 , ..., -6.99730132,
        -7.10798192, -6.93772711]])

In [151]:
vocab_to_coef = dict([(w, nb.coef_[0][s]) for w, s in vectoriser.vocabulary_.items()])

In [152]:
# top words:
# {"hiv", "vaginal", "tb", "tuberculosis", "viral"}

In [153]:
import operator

sorted(vocab_to_coef.items(), key=operator.itemgetter(1), reverse=True)

[('vaccine', -5.2749649276792585),
 ('malaria', -5.430387967685211),
 ('blood', -5.666759059599881),
 ('mda', -5.755196258836433),
 ('vaccination', -5.822980079869967),
 ('infants', -5.857028290171548),
 ('stool', -5.92075212744267),
 ('pregnancy', -6.035960253871302),
 ('azithromycin', -6.14557285085141),
 ('infection', -6.190056823184162),
 ('vaccines', -6.190249071146764),
 ('immunogenicity', -6.218887161487687),
 ('hiv', -6.221415830330172),
 ('placental', -6.243702353416717),
 ('village', -6.2549107645770174),
 ('vivax', -6.2664951069437365),
 ('rotavirus', -6.2942530312407525),
 ('food', -6.307495823771827),
 ('iron', -6.330310800018591),
 ('epi', -6.342831271802846),
 ('ultrasound', -6.351345755597877),
 ('plasmodium', -6.383380444575764),
 ('triple', -6.384950678389924),
 ('pr', -6.394248257705574),
 ('mg', -6.397381874350772),
 ('vitamin', -6.421399689317788),
 ('immunization', -6.422033287100643),
 ('parasite', -6.425873246686372),
 ('cholera', -6.438117974111424),
 ('screeni

In [154]:
sorted(vocab_to_coef.items(), key=operator.itemgetter(1))

[('inh', -7.138630926990997),
 ('quantiferon', -7.138630926990997),
 ('hvtn', -7.138630926990997),
 ('alvac', -7.138630926990997),
 ('aidsvax', -7.138630926990997),
 ('vrc', -7.138630926990997),
 ('ics', -7.138630926990997),
 ('rings', -7.138630926990997),
 ('mab', -7.138630926990997),
 ('genexpert', -7.138630926990997),
 ('mdr', -7.138630926990997),
 ('dst', -7.138630926990997),
 ('bdq', -7.138630926990997),
 ('bedaquiline', -7.138630926990997),
 ('aeras', -7.138630926990997),
 ('igra', -7.138630926990997),
 ('cld', -7.138630926990997),
 ('att', -7.138630926990997),
 ('qft', -7.138630926990997),
 ('shells', -7.138630926990997),
 ('ral', -7.138630926990997),
 ('dtg', -7.138630926990997),
 ('ltbi', -7.138630926990997),
 ('cascade', -7.138630926990997),
 ('youth', -7.138630926990997),
 ('actg', -7.138023639919389),
 ('bid', -7.137715350136209),
 ('sti', -7.137651070107874),
 ('mycobacterium', -7.137216031521083),
 ('pyrazinamide', -7.137161452594053),
 ('hsv', -7.136638719320908),
 ('amp

In [155]:
y_pred = model.predict(features_test)

In [156]:
y_pred

array([0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 2, 2])

In [157]:
labels_test

[0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 2, 2]

In [158]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [159]:
accuracy_score(labels_test, y_pred)

1.0

In [160]:
model.predict_proba(["hiv"])

array([[0.08541374, 0.69326162, 0.22132463]])

In [161]:
model.predict_proba(["potato"])

array([[0.31147541, 0.3442623 , 0.3442623 ]])

In [162]:
model.predict_log_proba(["potato"])

array([[-1.16643489, -1.06635143, -1.06635143]])

In [163]:
model.predict_log_proba(["hiv"])

array([[-2.46024825, -0.36634783, -1.50812473]])

In [164]:
import pickle as pkl
with open("condition_classifier.pkl", "wb") as f:
    pkl.dump(model, f)